# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0683014f49da95f5181753eb41c0f0a654de145957f6d26a866b347cfcf315be6424271574c43a6098d1af3e318da38b8dbce9b6c2b5fa230bf1cc8317eb9939

test:
  secret_key_base: b2c8b3ff8973070b9b04b781889dcec917fdda3db3e8d199d36a63d62ec35c00119e510c8b4462bb062ef9cc79caa020edaf75ecbbd5a7835dc3c93907b3a005

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
